version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./app
    ports:
      - "5001:5000"
    command: gunicorn --bind 0.0.0.0:5000 main:app
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8000:8000"
    depends_on:
      - flask_app