version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./app
    expose:
      - "5000"


  nginx:
    image: nginx:1.22.0
    container_name: nginx
    restart: always
    # build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/project.conf:/etc/nginx/conf.d/project.conf:ro
    ports:
      - "8000:8000"
    depends_on:
      - flask_app